### ISSUE TITLE
Migrate to Speedb

### ISSUE THREAD

**Issue by Jean-Lessa** [SparqNet/orbitersdk-cpp#31]
So this started as a "migrate to RocksDB" which is a drop-in replacement for LevelDB, but then I found a drop-in for the drop-in called [Speedb](https://www.speedb.io/), which touts itself as having "improved overall performance". Well, let's see how that goes.

We have three branches here for comparison:
- `main` (65e9ec1), with LevelDB 1.23 (from Debian Bookworm's repos)
- `rocksdb` (9cfec1a), with RocksDB 7.8.3 (from Debian Bookworm's repos)
- `speedb` (0656e7b), with Speedb 2.4.1 (from its respective Git tag, compiled from source, integrated within CMake)

Tests were made with 1000000 (one million) entries for each of the CRUD operations, both individual and batched, for both debug and release builds, and the databases were all at their "default settings" - this means no specific tuning for RocksDB or the others, they all ran OOTB (check [dbperf.patch.txt](https://github.com/SparqNet/orbitersdk-cpp/files/11510429/dbperf.patch.txt) for more info).

Results on my machine were as follows:

![bench](https://github.com/SparqNet/orbitersdk-cpp/assets/75625278/ac82823c-1f21-4238-ad51-955d29999d9b)

Knowing that Release is what matters the most, RocksDB proved itself to suck enough we can discard it entirely, but LevelDB vs Speedb is oddly confusing - where one excels in individual, creates and deletes, the other excels in batched, reads and updates. Overall there's a 15-20% perceived delta there, either negative or positive depending on who you're focusing.

A few other things we should know:

- I've tested with fewer entries before and it seems to be approximately proportional (e.g. if creating 1 million entries took ~400ms, creating 100000 took ~40ms, 10000 took ~4ms, etc., with a bit of wiggle room), so we could assume the following theoretical values for *one single individual read* operation for example, just for reference:
  - main debug - 6.226us
  - rocksdb debug - 2.885us
  - speedb debug - 4.089us
  - main release - 1.214us
  - rocksdb release - 1.157us
  - speedb release - 0.501us
- Based on the print, Speedb's deltas would be close to this (approx.):
  - [debug individual] - create: -200% | read: +34% | update: -243% | delete: -184%
  - [debug batched] - create: -174% | read: -60% | update: -55% | delete: -219%
  - [release individual] - create: -23% | read: +59% | update: -47% | delete: -22%
  - [release batched] - create: -14% | read: +17% | update: +51% | delete: -25%
- I've also tested smaller batches (10000 batches with 100 entries each, instead of one big batch with 1000000, check [dbperf2.patch.txt](https://github.com/SparqNet/orbitersdk-cpp/files/11510428/dbperf2.patch.txt) for more info) - batched read speeds were *atrocious* for some reason (to the point I actually had to abort them), but other batched operations had the following results:
  - [main release] - create: 263ms | update: 376ms | delete: 414ms
  - [speedb release] - create: 171ms | update: 368ms | delete: 206ms
- Speedb has support for Transactions (as it is a direct fork of RocksDB which also has), I haven't tested this
- Unlike LevelDB and RocksDB which can just be installed through Debian's `apt` repos, Speedb had to be integrated via CMake as an external project and *compiled from source* - for some reason their pre-built lib didn't work right for me (loads of "undefined reference" and "symbol relocation with -fPIE" or something), and because of that you need to run the build **twice** for it to work (because I don't know if there's a way to make CMake wait for an external project to finish compiling before going on)
- When testing the `speedb` branch, **remove RocksDB completely from your system** - for some oddball reason, even though I've completely eliminated any linkages to RocksDB within CMakeLists, when both are present there's a conflict which throws an AddressSanitizer error
- There could probably be ways to optimize all of this further, but I lack the knowledge on how (or *if*) it can be done

Honestly I don't know the answer to this one. We'd have to think a lot about our own needs, probably test things further or from another angle, and answer a few concepts:

1) What's more important for us right now - performance on create/delete, or on read/update?
2) How much weight does 1ms or even 1us have? Those deltas seem a bit high, around 50-200ms, and we can't really pick the best of both sides here
3) Are Speedb's Transactions a necessary thing to have? LevelDB doesn't have them, but we should consider whether this plus the "gains with losses and integration effort" we got with Speedb are actually worth the swap

**Comment by itamarcps** [comment]
Thank you for sharing the benchmark results. Looking at the data from release mode, disregarding debug as it's flags severely impact performance, it seems Speedb outperforms LevelDB in read and update operations, which are our primary focus. The slower individual updates on Speedb can be offset by maximizing batch processing. While Speedb lags slightly in create and delete operations, these differences are relatively small and don't significantly impact our overall performance needs. Speedb's transactional support will be later used within SafeVariables with DB instead temporary value.
