### ISSUE TITLE
Does it support decoding and encoding of tuple structures in ABI?

### ISSUE THREAD

**Issue by ykky0** [SparqNet/orbitersdk-cpp#47]
functionbulkRegister(string[],address,uint256,bytes32,address,bool,tuple(address,bytes32,uint256,uint256,bytes))

How can I properly decode and encode the tuple structure in the above ABI? Can you translate this text into English for me?

**Comment by itamarcps** [comment]
Hello! Currently explicitly using tuples (std::tuple) is not supported, we do plan to implement them soon (After contract reflections are implemented, which will remove the need to manually register functions and the contract in the CM).

Regardless of that, tuples in solidity are not proper types per say, they can only used to form syntactic groupings of expressions, meaning that your 

`functionbulkRegister(string[],address,uint256,bytes32,address,bool,tuple(address,bytes32,uint256,uint256,bytes))`

is actually

`functionbulkRegister(string[],address,uint256,bytes32,address,bool,address,bytes32,uint256,uint256,bytes)`

When encoding/decoding the ABI.
