### ISSUE TITLE
Tuple/Struct support

### ISSUE THREAD

**Issue by jcarraror** [SparqNet/orbitersdk-cpp#73]
- Motivation: Within the realm of blockchain development and especially within the constructs of smart contracts, the use of advanced data types like tuples/structs is inevitable. The capability to utilize such complex data structures allows developers to organize and manage data efficiently. Offering native support for tuple and struct types in OrbiterSDK will empower developers to build more sophisticated and feature-rich applications, fostering the development of advanced decentralized systems.

- Objective: Integrate native support for tuple/struct types within OrbiterSDK. This should allow developers to define, manipulate, and access these data types seamlessly, promoting the creation of intricate dApps and contracts that leverage the power of these data structures.

- Success Criteria: Developers should be able to:
  - Define tuple/struct data types within their contracts.
  - Access and modify the values within these types seamlessly.
  - Ensure compatibility and interoperability with other data types and features within OrbiterSDK.

- Dependencies: No dependencies.

- Risks and Mitigations:
  - Risk: Potential issues with memory management and storage, given that tuples can be more complex than primitive data types.
  - Mitigation: Implement rigorous testing and validation mechanisms to ensure optimal memory usage.
  - Risk: Ensuring that tuple types are compatible with existing features of OrbiterSDK without introducing vulnerabilities or inconsistencies.
  - Mitigation: Thoroughly review and test the integration of these types with existing OrbiterSDK functionalities.
  - Risk: Developer unfamiliarity or confusion about using these new data types.
  - Mitigation: Provide comprehensive documentation and example use-cases for integrating tuple and struct types.

- Resource Allocation: This task will require collaboration between core developers familiar with the OrbiterSDK's internal mechanics and those adept at C++ data structures. Given the intricacies of implementing advanced data types, a dedicated team for development, review, and testing will be essential. Proper time allocation for debugging and documentation is crucial to ensure a smooth integration of these data types into the SDK.

**Comment by itamarcps** [comment]
Tuple/struct support was implemented, closing issue.
