### ISSUE TITLE
Implement support for Solidity Events in the SDK

### ISSUE THREAD

**Issue by jcarraror** [SparqNet/orbitersdk-cpp#75]
- **Motivation**: Solidity events provide a logging mechanism for applications frontend to "listen" to changes happening in contracts on the blockchain. They play an essential role in DApps by enabling reactive behaviors based on contract activities. By integrating support for Solidity Events in OrbiterSDK, we will make the SDK more compatible and user-friendly for developers who are accustomed to Ethereum's development patterns, thereby promoting adoption and extending the utility of the SDK.

- **Objective**: Implement native support for Solidity Events within OrbiterSDK. Developers should be able to declare, emit, and listen to events as they would in a typical Ethereum-based environment.

- **Success Criteria**:
  1. Define and emit events within contracts developed using OrbiterSDK.
  2. Frontend DApps or other applications should be able to efficiently listen to and capture these emitted events.
  3. Ensure that emitted events are stored and retrievable from the blockchain logs.

- **Dependencies**:  None

- **Risks and Mitigations**: 
  - **Risk**: Performance overhead due to logging and storing events on the blockchain.
    - **Mitigation**: Implement efficient storage and retrieval mechanisms, possibly using optimized data structures or compression techniques.
  - **Risk**: Compatibility issues if the Solidity Events implementation is not in sync with standard Ethereum behavior.
    - **Mitigation**: Rigorous testing using existing Ethereum contracts and ensuring the behavior of events is consistent with Ethereum standards.
  - **Risk**: Ensuring the security of logs and prevention of unauthorized access or tampering.
    - **Mitigation**: Implement encryption and validation mechanisms for event logs.

- **Resource Allocation**:  A dedicated team comprising developers should be allocated to ensure accurate implementation. Additionally, time should be allocated for comprehensive documentation to guide developers in using events within their applications and contracts.

---

**Comment by Jean-Lessa** [comment]
I don't get why Github never cared to show commits here, but anyway #82 was created so we can close this issue if it gets approved.
